version: '3'

services:
    postgres:
        container_name: 'logistics-manager-postgres'
        build:
            context: ./.docker/postgres
            dockerfile: Dockerfile
        restart: always
        shm_size: 4g
        ports:
            - 5434:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data:rw"
        environment:
            - POSTGRES_DB=logistics-manager
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=123456789
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_HOST_AUTH_METHOD=trust

    php:
        build: .docker/php
        container_name: 'logistics-manager-php'
        volumes:
            - .:/var/www/html/logistics-manager
        links:
            - postgres
        depends_on:
            - php-build

    php-build:
        image: php
        build: .docker/php
        container_name: 'logistics-manager-php-build'
        volumes:
            - .:/var/www/html/logistics-manager
        links:
            - postgres
        command: >
            bash -c "cd /var/www/html/logistics-manager && composer setup"

    nginx:
        build:
            context: .docker
            dockerfile: nginx/Dockerfile
        container_name: 'logistics-manager-nginx'
        ports:
            - 8013:80
        depends_on:
            - php
        volumes:
            - .:/var/www/html/logistics-manager

volumes:
    postgres:
        driver: local
    php:
        driver: local
    redis:
        driver: local
